// <auto-generated />
using HelloWorld.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelloWorld.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20240320113857_initDB")]
    partial class initDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("HelloWorld.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Category 1"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Category 2"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Category 3"
                        });
                });

            modelBuilder.Entity("HelloWorld.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Description = "Desc of Product 1",
                            Name = "Product 1",
                            Price = 0.0
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 1,
                            Description = "Desc of Product 2",
                            Name = "Product 2",
                            Price = 0.0
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 1,
                            Description = "Desc of Product 3",
                            Name = "Product 3",
                            Price = 0.0
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 1,
                            Description = "Desc of Product 4",
                            Name = "Product 4",
                            Price = 0.0
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 2,
                            Description = "Desc of Product 5",
                            Name = "Product 5",
                            Price = 0.0
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 2,
                            Description = "Desc of Product 6",
                            Name = "Product 6",
                            Price = 0.0
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 2,
                            Description = "Desc of Product 7",
                            Name = "Product 7",
                            Price = 0.0
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 2,
                            Description = "Desc of Product 8",
                            Name = "Product 8",
                            Price = 0.0
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 2,
                            Description = "Desc of Product 9",
                            Name = "Product 9",
                            Price = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
